status = [
    'Tests on ubuntu-22.04',
    'Tests on macos-13',
    'Tests on windows-2022',
    'Run Clippy',
    'Run Rustfmt',
    'Run tests in debug',
    'Check db change labels',
]
# 3 hours timeout
timeout-sec = 10800
